### PR TITLE
[HPRO-882] Add new login splash page

### PR DESCRIPTION
**Pull request by stephenyeargin**
| Q                   | A
| ------------------- | --------------
| Target Release?     | Next available 
| Bug fix?            | ❌ 
| New feature?        | ✅ 
| Database migration? | ❌ 
| New configuration?  | ❌ 
| Composer updates?   | ❌ 
| NPM updates?        | ❌ 
| Jira Ticket(s)      | HPRO-882 

### Summary

Prior to this PR, the default behavior was to take the user directly to the Google sign-in routine when visiting the site as an unauthenticated user. This changes that to show a landing page with support information.

### Screenshots 

**Full Size**

localhost_8080_s_login

**Tablet**

localhost_8080_s_login (1)

**Mobile Screen**

localhost_8080_s_login (2)

### CODE REVIEW

**Review by shyamnaru — APPROVED** [review]

**Review by jt2k — COMMENTED** [review]
I don't know that we have this documented anywhere, but we have all of our existing HTML/Twig and CSS files indented with 4 spaces. Can you fix the indentation on the two files? Other than that, looks good!

**Comment by stephenyeargin** [comment]
> I don't know that we have this documented anywhere, but we have all of our existing HTML/Twig and CSS files indented with 4 spaces. Can you fix the indentation on the two files? Other than that, looks good!

Added an entry in `.editorconfig` in 1f12011, adjusted whitespace in 593cd4f

**Comment by jt2k** [comment]
> Added an entry in `.editorconfig` in [1f12011](https://github.com/all-of-us/healthpro/commit/1f120112ca310480f9c2e212e589b5fcf3956d8e), adjusted whitespace in [593cd4f](https://github.com/all-of-us/healthpro/commit/593cd4f3dde44b3529dafeb0b889a99089d1d276)

Thanks! Can you do the same for the CSS file, too?

**Comment by stephenyeargin** [comment]
> Thanks! Can you do the same for the CSS file, too?

Done in aa4119f7

**Review by jt2k — APPROVED** [review]

**Pull request merged**
